spring:
  datasource:
    url: jdbc:mysql://localhost:3306/usedCar?serverTimezone=UTC
    username: root
    password: 12345678

mybatis:
  config-location: classpath:mybatis/config/config.xml

  springdoc:
    swagger-ui:
      path: /swagger-ui.html
